### ISSUE TITLE
Falta LICENSE.md

### ISSUE THREAD

**Issue by amafoas** [GDevatanian/Multicalc#1]
Hola, vi que decís que tu proyecto está bajo la Licencia del MIT, pero no hay ningún archivo LICENSE.md para revisar.

**Comment by GDevatanian** [comment]
Hola. Analizamos el issue y el ETA para los cambios solicitados lo tenemos planeado para Q3 de este año! Muchas gracias por levantar el issue. Saludos desde el equipo de Multicalc!
